
'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

// Schema for initial customer creation (Banker side)
const createCustomerSchema = z.object({
    firstName: z.string().min(1, 'First name is required'),
    lastName: z.string().min(1, 'Last name is required'),
    email: z.string().email('Invalid email address'),
    // password is NOT required here, it's set by customer later
    dateOfBirth: z.string().min(1, 'Date of birth is required'), // simplified for UI, parsed by API
    customerNumber: z.string().min(1, 'Customer Number (CIF) is required'), // Ideally auto-generated by backend, but for now manual or pre-gen
});

type CreateForm = z.infer<typeof createCustomerSchema>;

export default function NewCustomerPage() {
    const router = useRouter();
    const [error, setError] = useState<string | null>(null);
    const [submitting, setSubmitting] = useState(false);

    const { register, handleSubmit, formState: { errors } } = useForm<CreateForm>({
        resolver: zodResolver(createCustomerSchema),
    });

    const onSubmit = async (data: CreateForm) => {
        setSubmitting(true);
        setError(null);
        try {
            // We need an API endpoint for creating a customer (without password).
            // Currently src/app/api/v1/customers usually requires password.
            // We might need a specific banker endpoint: POST /api/v1/banker/customers
            const res = await fetch('/api/v1/banker/customers/create', { // New endpoint needed
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data),
            });

            const result = await res.json();

            if (!res.ok) {
                throw new Error(result.error || 'Failed to create customer');
            }

            // Success -> Redirect to customer list to generate link
            router.push('/banker/customers');
        } catch (err: any) {
            setError(err.message);
        } finally {
            setSubmitting(false);
        }
    };

    return (
        <div className="max-w-2xl mx-auto py-8">
            <div className="mb-6">
                <h1 className="text-2xl font-bold text-slate-900">New Customer Onboarding</h1>
                <p className="text-slate-600">Create a customer record to begin the onboarding process.</p>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Customer Details</CardTitle>
                    <CardDescription>Enter the customer's basic information.</CardDescription>
                </CardHeader>
                <CardContent>
                    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
                        {error && (
                            <Alert variant="destructive">
                                <AlertDescription>{error}</AlertDescription>
                            </Alert>
                        )}

                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="firstName">First Name</Label>
                                <Input id="firstName" {...register('firstName')} />
                                {errors.firstName && <span className="text-sm text-red-500">{errors.firstName.message}</span>}
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="lastName">Last Name</Label>
                                <Input id="lastName" {...register('lastName')} />
                                {errors.lastName && <span className="text-sm text-red-500">{errors.lastName.message}</span>}
                            </div>
                        </div>

                        <div className="space-y-2">
                            <Label htmlFor="email">Email Address</Label>
                            <Input id="email" type="email" {...register('email')} />
                            {errors.email && <span className="text-sm text-red-500">{errors.email.message}</span>}
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div className="space-y-2">
                                <Label htmlFor="dateOfBirth">Date of Birth</Label>
                                <Input id="dateOfBirth" type="date" {...register('dateOfBirth')} />
                                {errors.dateOfBirth && <span className="text-sm text-red-500">{errors.dateOfBirth.message}</span>}
                            </div>
                            <div className="space-y-2">
                                <Label htmlFor="customerNumber">Customer Number (CIF)</Label>
                                <Input id="customerNumber" {...register('customerNumber')} placeholder="e.g. 1000005" />
                                {errors.customerNumber && <span className="text-sm text-red-500">{errors.customerNumber.message}</span>}
                            </div>
                        </div>

                        <div className="pt-4 flex justify-end gap-2">
                            <Button variant="outline" type="button" onClick={() => router.back()}>Cancel</Button>
                            <Button type="submit" disabled={submitting}>
                                {submitting ? 'Creating...' : 'Create Record'}
                            </Button>
                        </div>
                    </form>
                </CardContent>
            </Card>
        </div>
    );
}
